version: "3"

services:
  app:
    container_name: request-tester
    image: request-tester:latest
    build: .
    restart: always
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - .:/app
